CREATE TYPE IF NOT EXISTS orderstatus AS ENUM ('NEW', 'PROCESSING', 'INVALID', 'PROCESSED');
ALTER TABLE orders
ADD COLUMN IF NOT EXISTS accrual INTEGER DEFAULT 0 NULL;
ALTER TABLE orders
ADD COLUMN IF NOT EXISTS status orderstatus DEFAULT 'NEW' NOT NULL;
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);
UPDATE orders SET status = 'NEW' WHERE status IS NULL;
