DO $$
BEGIN
    CREATE TYPE orderstatus AS ENUM ('NEW', 'PROCESSING', 'INVALID', 'PROCESSED');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

ALTER TABLE orders ADD COLUMN IF NOT EXISTS accrual INTEGER DEFAULT 0;

ALTER TABLE orders ADD COLUMN IF NOT EXISTS status orderstatus DEFAULT 'NEW';

ALTER TABLE orders ALTER COLUMN status SET NOT NULL;

CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);
UPDATE orders SET status = 'NEW' WHERE status IS NULL;
