CREATE TABLE orders (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    order_num INTEGER NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    uploaded_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    FOREIGN KEY (user_id) REFERENCES user(id),
);

